<a href="https://colab.research.google.com/github/SatyamRudrakanthwar/Rock-and-mine-prediction-using-Logistic-Regression/blob/main/some_questions_of_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Create two NumPy arrays with different shapes
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([10, 20, 30])

# Perform element-wise addition using broadcasting
result = array1 + array2

# Display the result
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nResult of broadcasting:")
print(result)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[10 20 30]

Result of broadcasting:
[[11 22 33]
 [14 25 36]]


In [4]:
import numpy as np

# Create a NumPy array with little-endian byte order
data = np.array([0x123456789abcdef0], dtype=np.uint64)
print("Original data:")
print(data)

# Byte swap the array (change the byte order to big-endian)
swapped_data = data.byteswap()
print("\nByte-swapped data:")
print(swapped_data)

# Alternatively, you can use the newbyteorder() function
# to explicitly specify the byte order you want
swapped_data2 = data.newbyteorder('big')
print("\nByte-swapped data using newbyteorder():")
print(swapped_data2)

Original data:
[1311768467463790320]

Byte-swapped data:
[17356517385562371090]

Byte-swapped data using newbyteorder():
[17356517385562371090]


In [5]:
import numpy as np

# Creating an original array
original_array = np.array([[1, 2, 3],
                           [4, 5, 6]])

# Creating a copy of the original array
copy_array = original_array.copy()

# Creating a view of the original array
view_array = original_array.view()

# Modifying elements in the copy array
copy_array[0, 0] = 100

# Modifying elements in the view array
view_array[1, 1] = 200

# Display the original, copy, and view arrays
print("Original Array:")
print(original_array)

print("\nCopy Array:")
print(copy_array)

print("\nView Array:")
print(view_array)

Original Array:
[[  1   2   3]
 [  4 200   6]]

Copy Array:
[[100   2   3]
 [  4   5   6]]

View Array:
[[  1   2   3]
 [  4 200   6]]


In [6]:
import numpy as np

# Creating an array of angles in degrees
angles_deg = np.array([0, 30, 45, 60, 90])

# Convert angles to radians
angles_rad = np.radians(angles_deg)

# Trigonometric functions
sine_values = np.sin(angles_rad)
cosine_values = np.cos(angles_rad)
tangent_values = np.tan(angles_rad)
arcsine_values = np.arcsin(sine_values)
arccosine_values = np.arccos(cosine_values)
arctangent_values = np.arctan(tangent_values)

# Display the results
print("Angles (in degrees):", angles_deg)
print("Angles (in radians):", angles_rad)
print("Sine values:", sine_values)
print("Cosine values:", cosine_values)
print("Tangent values:", tangent_values)
print("Arcsine values:", arcsine_values)
print("Arccosine values:", arccosine_values)
print("Arctangent values:", arctangent_values)

Angles (in degrees): [ 0 30 45 60 90]
Angles (in radians): [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Sine values: [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine values: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tangent values: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
Arcsine values: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Arccosine values: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Arctangent values: [0.         0.52359878 0.78539816 1.04719755 1.57079633]


In [7]:
import numpy as np

# Create a sample array for demonstration
data = np.array([12, 45, 23, 67, 89, 34, 56, 78, 90, 43])

# Statistical Functions
mean_value = np.mean(data)
median_value = np.median(data)
standard_deviation = np.std(data)
variance = np.var(data)
min_value = np.min(data)
max_value = np.max(data)
sum_value = np.sum(data)

# Display the results
print("Data:", data)
print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", standard_deviation)
print("Variance:", variance)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)
print("Sum of Values:", sum_value)

Data: [12 45 23 67 89 34 56 78 90 43]
Mean: 53.7
Median: 50.5
Standard Deviation: 25.682873670989387
Variance: 659.6099999999999
Minimum Value: 12
Maximum Value: 90
Sum of Values: 537


In [8]:
import numpy as np

# Create two NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([10, 20, 30, 40, 50])

# Perform element-wise addition using vectorization
result_addition = array1 + array2

# Perform element-wise subtraction using vectorization
result_subtraction = array1 - array2

# Perform element-wise multiplication using vectorization
result_multiplication = array1 * array2

# Perform element-wise division using vectorization
result_division = array2 / array1

# Display the results
print("Array 1:", array1)
print("Array 2:", array2)

print("\nElement-wise Addition Result:", result_addition)
print("Element-wise Subtraction Result:", result_subtraction)
print("Element-wise Multiplication Result:", result_multiplication)
print("Element-wise Division Result:", result_division)

Array 1: [1 2 3 4 5]
Array 2: [10 20 30 40 50]

Element-wise Addition Result: [11 22 33 44 55]
Element-wise Subtraction Result: [ -9 -18 -27 -36 -45]
Element-wise Multiplication Result: [ 10  40  90 160 250]
Element-wise Division Result: [10. 10. 10. 10. 10.]
